//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CurrencyConverterTool.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class SourceAPIMaster
    {
        public int ID { get; set; }
        public string SourceAPIName { get; set; }
        public string SourceAPIClassName { get; set; }
        public string SourceAPIURL { get; set; }
        public bool IsFromCurrencyRequired { get; set; }
        public bool IsToCurrencyRequired { get; set; }
        public bool IsAmountRequired { get; set; }
        public bool IsConversionDateRequired { get; set; }
        public bool IsActiveAPI { get; set; }
    }
}
